apiVersion: v1
kind: Pod
metadata:
  name: student-db-pod
spec:
  containers:
    - name: student-db-container
      image: mysql:latest
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: student-db-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: student-db-secret
              key: DB_NAME

