apiVersion: v1
kind: Secret
metadata:
  name: student-db-secret
type: Opaque
data:
  DB_HOST: MTcyLjI3LjEwNy4zMQ==    # Base64 encoded value of '172.27.107.31'
  DB_USER: cm9vdA==               # Base64 encoded value of 'root'
  DB_PASSWORD: U2Fuc2tydXRpQDEyMw==  # Base64 encoded value of 'Sanskruti@123'
  DB_NAME: c3R1ZGVudF9kYg==       # Base64 encoded value of 'student_db'
