apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
spec:
  replicas: 2  # Run 2 pods for redundancy
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      containers:
        - name: student-api
          image: your-dockerhub-username/student-api:latest  # Change this to your image
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: student-db-secret
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: student-db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: student-db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: student-db-secret
                  key: DB_NAME
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: student-config
                  key: FLASK_ENV
