apiVersion: v1
kind: Secret
metadata:
  name: student-db-secret
type: Opaque
data:
  DB_HOST: MTcyLjI3LjEwNy4zMQ==    # Base64 encoded (172.27.107.31)
  DB_USER: cm9vdA==               # Base64 encoded (root)
  DB_PASSWORD: U2Fuc2tydXRpQDEyMw==  # Base64 encoded (Sanskruti@123)
  DB_NAME: c3R1ZGVudF9kYg==       # Base64 encoded (student_db)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: student-config
data:
  FLASK_ENV: "production"
  FLASK_APP: "app.py"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
spec:
  replicas: 2  # Run 2 pods for redundancy
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      containers:
        - name: student-api
          image: sanskrutipawar/student-management:latest  # Ensure this image is pushed to Docker Hub
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: student-db-secret
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: student-db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: student-db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: student-db-secret
                  key: DB_NAME
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: student-config
                  key: FLASK_ENV
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: student-api-service
spec:
  selector:
    app: student-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort  # Changed from ClusterIP for easier access in Minikube